language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=6.9.5
   
install:
  - nvm install $NODE_VERSION
  - npm install
 
before_install:
    - "nvm install $NODE_VERSION"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "npm install -g npm@3"
    - "webdriver-manager update"

script: "npm test"
